// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	getEnvPlatformInfo: () => typedError<EnvPlatformInfo, EnvCommandError>(__TAURI_INVOKE("get_env_platform_info")),
	listEnvVars: () => typedError<ListEnvResult, EnvCommandError>(__TAURI_INVOKE("list_env_vars")),
	getEnvVar: (key: string) => typedError<GetEnvResult, EnvCommandError>(__TAURI_INVOKE("get_env_var", { key })),
	previewEnvWrite: (request: PreviewEnvWriteRequest) => typedError<EnvWritePreview, EnvCommandError>(__TAURI_INVOKE("preview_env_write", { request })),
	previewEnvDelete: (request: PreviewEnvDeleteRequest) => typedError<EnvWritePreview, EnvCommandError>(__TAURI_INVOKE("preview_env_delete", { request })),
	applyEnvWrite: (request: ApplyEnvWriteRequest) => typedError<SetEnvResult, EnvCommandError>(__TAURI_INVOKE("apply_env_write", { request })),
	/**  识别鼠标点下的元素（控件级优先，窗口级兜底）。 */
	elementFromPoint: (point: PhysicalDesktopPointI32) => typedError<{
	left: number,
	top: number,
	right: number,
	bottom: number,
	controlType: number,
	name: string,
	/**  true = 顶层窗口（控件级识别失败时的降级结果）。 */
	isWindow: boolean,
	/**
	 *  包含该元素的顶层窗口矩形（物理像素）。窗口级识别时为 None（自身即窗口）。
	 *  前端用它做「控件所在窗口去阴影」。
	 */
	windowRect: [number, number, number, number] | null,
} | null, string>(__TAURI_INVOKE("element_from_point", { point })),
	/**
	 *  OCR 识别 PNG 图片（截图选区 / 独立工具共用）。
	 * 
	 *  `mode`：`best`（精准，默认）或 `fast`（快速）。两种模式的引擎分别缓存。
	 * 
	 *  异步命令：同步阻塞的引擎初始化与识别都经 `spawn_blocking` 放到线程池，
	 *  避免冻结 UI 线程。
	 */
	ocrRecognizePng: (png: number[], mode: string | null) => typedError<OcrResult, string>(__TAURI_INVOKE("ocr_recognize_png", { png, mode })),
	/**  读取密码库（解密 / 迁移后返回 JSON 字符串；不存在返回 `None`）。 */
	pwdboxLoad: () => typedError<string | null, string>(__TAURI_INVOKE("pwdbox_load")),
	/**  加密并落盘密码库 JSON 字符串。 */
	pwdboxSave: (data: string) => typedError<null, string>(__TAURI_INVOKE("pwdbox_save", { data })),
	/**  读取 Curl 请求历史（解密 / 迁移后返回 JSON 字符串；不存在返回 `None`）。 */
	curlStorageLoad: () => typedError<string | null, string>(__TAURI_INVOKE("curl_storage_load")),
	/**  加密并落盘 Curl 请求历史 JSON 字符串。 */
	curlStorageSave: (data: string) => typedError<null, string>(__TAURI_INVOKE("curl_storage_save", { data })),
	historyGetQuotaSettings: () => typedError<HistoryQuotaSettings, string>(__TAURI_INVOKE("history_get_quota_settings")),
	historySetQuotaSettings: (quotaBytes: number) => typedError<HistoryQuotaSettings, string>(__TAURI_INVOKE("history_set_quota_settings", { quotaBytes })),
	historyListRecords: () => typedError<HistoryRecordSummary[], string>(__TAURI_INVOKE("history_list_records")),
	historyGetRecord: (recordId: string) => typedError<HistoryRecordDetail, string>(__TAURI_INVOKE("history_get_record", { recordId })),
	historyReadImageToken: (token: string) => typedError<number[], string>(__TAURI_INVOKE("history_read_image_token", { token })),
	/**
	 *  Returns a compact final-image thumbnail for history list navigation.
	 *  The dimensions are fixed server-side so callers cannot request unbounded
	 *  image processing work or accidentally load every full-resolution PNG.
	 */
	historyReadThumbnail: (recordId: string) => typedError<number[], string>(__TAURI_INVOKE("history_read_thumbnail", { recordId })),
	historySaveAs: (recordId: string, variant: HistoryImageVariant) => typedError<HistorySaveAsResult, string>(__TAURI_INVOKE("history_save_as", { recordId, variant })),
	/**
	 *  Creates an independent history record from a selected source image. The
	 *  annotation editor can later modify this copy without mutating its source.
	 */
	historyCreateCopyFromRecord: (recordId: string, variant: HistoryImageVariant) => typedError<HistoryRecordSummary, string>(__TAURI_INVOKE("history_create_copy_from_record", { recordId, variant })),
	historyDeleteRecord: (recordId: string) => typedError<TrashReceipt, string>(__TAURI_INVOKE("history_delete_record", { recordId })),
	historyUndoDelete: (recordId: string) => typedError<HistoryRecordSummary, string>(__TAURI_INVOKE("history_undo_delete", { recordId })),
	historyClearAll: () => typedError<number, string>(__TAURI_INVOKE("history_clear_all")),
	historyRevealRecord: (recordId: string) => typedError<null, string>(__TAURI_INVOKE("history_reveal_record", { recordId })),
	pinCreateFromHistory: (recordId: string, variant: HistoryImageVariant) => typedError<PinCreateResult, string>(__TAURI_INVOKE("pin_create_from_history", { recordId, variant })),
	pinList: () => typedError<PinTrayItem[], string>(__TAURI_INVOKE("pin_list")),
	pinGetState: (pinId: string) => typedError<PinState, string>(__TAURI_INVOKE("pin_get_state", { pinId })),
	pinReadImage: (pinId: string, imageToken: string) => typedError<number[], string>(__TAURI_INVOKE("pin_read_image", { pinId, imageToken })),
	pinSetZoom: (pinId: string, zoomPercent: number) => typedError<PinState, string>(__TAURI_INVOKE("pin_set_zoom", { pinId, zoomPercent })),
	/**  旋转贴图（0/90/180/270）。CSS transform 视觉旋转，窗口矩形不变。 */
	pinSetRotation: (pinId: string, rotation: number) => typedError<PinState, string>(__TAURI_INVOKE("pin_set_rotation", { pinId, rotation })),
	/**  翻转贴图（水平/垂直）。CSS transform，窗口矩形不变。 */
	pinSetFlip: (pinId: string, horizontal: boolean, vertical: boolean) => typedError<PinState, string>(__TAURI_INVOKE("pin_set_flip", { pinId, horizontal, vertical })),
	/**  贴图分组（0/1/2）。分组后可用 `pin_set_group_visible` 整体显隐。 */
	pinSetGroup: (pinId: string, group: number) => typedError<PinState, string>(__TAURI_INVOKE("pin_set_group", { pinId, group })),
	pinSetOpacity: (pinId: string, opacityPercent: number) => typedError<PinState, string>(__TAURI_INVOKE("pin_set_opacity", { pinId, opacityPercent })),
	pinReset: (pinId: string) => typedError<PinState, string>(__TAURI_INVOKE("pin_reset", { pinId })),
	pinSetClickThrough: (pinId: string, enabled: boolean) => typedError<PinState, string>(__TAURI_INVOKE("pin_set_click_through", { pinId, enabled })),
	pinEnableAllInteraction: () => typedError<number, string>(__TAURI_INVOKE("pin_enable_all_interaction")),
	pinStartDrag: (pinId: string) => typedError<null, string>(__TAURI_INVOKE("pin_start_drag", { pinId })),
	pinClose: (pinId: string) => typedError<boolean, string>(__TAURI_INVOKE("pin_close", { pinId })),
	pinCloseAll: () => typedError<number, string>(__TAURI_INVOKE("pin_close_all")),
	/**  开始滚动截图会话（async：创建 HUD 窗口需要与消息循环协调）。 */
	scrollCaptureStart: (selection: PhysicalDesktopRectI32) => typedError<ScrollStartResult, string>(__TAURI_INVOKE("scroll_capture_start", { selection })),
	/**  采集一步并拼接（async 避免阻塞主线程）。手动滚动模式：不自动滚动。 */
	scrollCaptureNext: () => typedError<ScrollProgress, string>(__TAURI_INVOKE("scroll_capture_next")),
	/**  停止滚动截图会话，把拼接结果存入独立存储（与「会话进行中」解耦）。 */
	scrollCaptureStop: () => typedError<ScrollStopResult, string>(__TAURI_INVOKE("scroll_capture_stop")),
	/**
	 *  完成滚动截图（history-first 事务）。
	 * 
	 *  拼接长图由后端从结果存储取用（长图可能超大，前端不传输），original 与
	 *  final 均为拼接长图。副作用（Copy/Pin/SaveAs）在历史发布成功后执行。
	 */
	scrollCaptureFinish: (action: "copy" | "pin" | "save_as" | null) => typedError<ConfirmSelectionResult, string>(__TAURI_INVOKE("scroll_capture_finish", { action })),
	/**
	 *  发布滚动截图到历史（不执行副作用），返回 record_id。
	 * 
	 *  供「保存」动作使用：先发布历史拿到 recordId，再走 `history_save_as`。
	 */
	scrollCapturePublish: () => typedError<ScrollPublishResult, string>(__TAURI_INVOKE("scroll_capture_publish")),
	/**  查询是否存在待展示的滚动截图结果（供主窗口恢复后主动获取）。 */
	scrollCaptureHasResult: () => typedError<string | null, string>(__TAURI_INVOKE("scroll_capture_has_result")),
	/**  取消滚动截图会话（放弃，不发布历史）。 */
	scrollCaptureCancel: () => typedError<null, string>(__TAURI_INVOKE("scroll_capture_cancel")),
	/**
	 *  开始一次全平台截图会话。
	 * 
	 *  Windows 上建窗会与消息循环冲突，因此必须是 async 命令（wry 的
	 *  CreateCoreWebView2Environment 需要 pump 消息；async 让命令在 worker
	 *  线程运行，由 send_user_message 派发到事件循环）。
	 */
	screenshotUniversalStart: () => typedError<StartOverlaySession, string>(__TAURI_INVOKE("screenshot_universal_start")),
	/**  按 token 读取采集帧（编码为 PNG 字节）。 */
	screenshotUniversalReadFrame: (token: string) => typedError<number[], string>(__TAURI_INVOKE("screenshot_universal_read_frame", { token })),
	/**  取消全平台截图会话：关闭覆盖层、恢复主窗口。 */
	screenshotUniversalCancel: (sessionId: string | null) => typedError<CancelSessionResult, string>(__TAURI_INVOKE("screenshot_universal_cancel", { sessionId })),
	/**
	 *  完成一次全平台截图会话。
	 * 
	 *  前端已在覆盖层内完成选区与标注，并导出两个 PNG：
	 *  - `original_png`：未标注的裁剪结果（采集帧按选区裁剪）。
	 *  - `final_png`：标注后的最终图（前端 canvas 出图）。
	 * 
	 *  完成事务是 history-first：先发布历史记录，成功后再执行副作用
	 *  （复制 / 贴图 / 另存为）。副作用失败保留会话可重试。
	 */
	screenshotUniversalFinish: (sessionId: string, originalPng: number[], finalPng: number[], action: "copy" | "pin" | "save_as" | null) => typedError<ConfirmSelectionResult, string>(__TAURI_INVOKE("screenshot_universal_finish", { sessionId, originalPng, finalPng, action })),
	/**
	 *  覆盖层窗口挂载时查询自己的会话信息。
	 * 
	 *  每个覆盖层窗口是独立 WebView，通过窗口 label（`overlay-<index>`）识别
	 *  自己的显示器索引，向后端查询对应的采集帧访问 token 与桌面矩形。
	 */
	screenshotUniversalOverlayInit: () => typedError<OverlayInitInfo, string>(__TAURI_INVOKE("screenshot_universal_overlay_init")),
	/**  获取配置（工具页/弹窗初始化）。读取 store 权威数据，失败回退默认值。 */
	sedentaryGetConfig: () => typedError<SedentaryGetConfigResponse, string>(__TAURI_INVOKE("sedentary_get_config")),
	/**  更新配置并持久化；`remindMinutes`/`idleResetMinutes` 变更时重置当前计时。 */
	sedentarySetConfig: (enabled: boolean | null, remindMinutes: number | null, idleResetMinutes: number | null, message: string | null, videoEnabled: boolean | null, quietPeriods: QuietPeriod[] | null) => typedError<null, string>(__TAURI_INVOKE("sedentary_set_config", { enabled, remindMinutes, idleResetMinutes, message, videoEnabled, quietPeriods })),
	/**  获取实时状态（工具页轮询）。 */
	sedentaryGetState: () => typedError<SedentaryGetStateResponse, string>(__TAURI_INVOKE("sedentary_get_state")),
	/**
	 *  弹窗按钮动作：`got_up` = 已起身（重置计时并关窗）；`snooze` = 稍后（关窗，
	 *  5 分钟后再次提醒，计时持续累计）。
	 *  仅 Windows：动作作用于久坐提醒弹窗，该弹窗仅在 Windows 存在。
	 */
	sedentaryRemindAction: (action: string) => typedError<null, string>(__TAURI_INVOKE("sedentary_remind_action", { action })),
	/**
	 *  总开关（托盘/工具页）。关闭时计时归零并关掉已开弹窗。
	 *  仅 Windows：开关与空闲检测轮询/弹窗绑定，非 Windows 前端以 `supported: false` 禁用。
	 */
	sedentaryToggle: (enabled: boolean) => typedError<null, string>(__TAURI_INVOKE("sedentary_toggle", { enabled })),
	/**
	 *  预览提醒弹窗：直接弹出与真实提醒完全一致的窗口，便于验收效果。
	 * 
	 *  仅预览用途：不记录 `last_remind_at`、不消耗冷却期，也不影响真实触发逻辑
	 *  （真实提醒仍由轮询线程的 `trigger_reminder` 驱动）。
	 */
	sedentaryPreview: () => typedError<null, string>(__TAURI_INVOKE("sedentary_preview")),
	/**
	 *  `sedentary_set_user_video`：把用户选择的本地视频复制为自定义提醒视频
	 *  （`app_local_data_dir()/sedentary-video/user-video.mp4`，覆盖式只保留最新
	 *  一个）。返回复制后的视频绝对路径；超限（> 20MB）/ 非白名单扩展名 / 非文件 /
	 *  复制失败返回错误。
	 * 
	 *  安全说明：命令接收任意本地路径并复制到 asset scope。Rust 无法获知路径是否
	 *  来自原生对话框，故做来源强校验：源必须是**文件**（非目录）、扩展名在
	 *  mp4/webm/mov 白名单内（与前端对话框过滤器一致）、且大小 ≤ 20MB。
	 *  复制方向固定为「本地源 → 应用数据目录」，不会从 asset scope 反向覆盖系统
	 *  关键目录；扩展名+大小约束也把「复制任意文件」的风险限制在小型媒体文件。
	 */
	sedentarySetUserVideo: (sourcePath: string) => typedError<string, string>(__TAURI_INVOKE("sedentary_set_user_video", { sourcePath })),
	/**
	 *  `sedentary_reset_user_video`：删除自定义视频（若有），回退到默认源视频
	 *  （`ensure_reminder_video` 会重新复制固定源；源缺失则回退无视频模式）。
	 * 
	 *  返回恢复后的视频绝对路径（无视频模式返回空串）。
	 */
	sedentaryResetUserVideo: () => typedError<string, string>(__TAURI_INVOKE("sedentary_reset_user_video")),
	/**
	 *  贴出一个便利贴窗口（创建新便利贴或恢复已存的）。
	 * 
	 *  - `note: None`：新建便利贴（快捷键入口），生成唯一 `sn-<uuid>` 并写 store。
	 *  - `note: Some(n)`：恢复已存便利贴。会从 store 取**权威数据**（避免传入的
	 *    过期/脏数据），并校验便利贴确实存在——若已被删除则返回错误，避免贴出
	 *    一个「加载不到数据的空白窗口」。
	 * 
	 *  async：创建 WebView 窗口较慢，放后台线程避免阻塞主线程（同 pin_create_from_history）。
	 */
	stickyCreate: (note: {
	id: string,
	text: string,
	/**  预设色 key（mint/yellow/blue/pink/purple）。 */
	color: string,
	/**  分组名。 */
	group: string,
	x: number,
	y: number,
	width: number,
	height: number,
} | null) => typedError<StickyNoteData, string>(__TAURI_INVOKE("sticky_create", { note })),
	/**  便利贴列表（管理入口）。 */
	stickyList: () => typedError<StickyNoteData[], string>(__TAURI_INVOKE("sticky_list")),
	/**
	 *  更新便利贴（自动保存：文本/颜色/分组/位置/大小）。
	 * 
	 *  同一 id 只保留一份（upsert_note 去重）；id 不存在则追加。所有读-改-写串行化。
	 */
	stickyUpdate: (note: StickyNoteData) => typedError<null, string>(__TAURI_INVOKE("sticky_update", { note })),
	/**
	 *  删除便利贴（从 store 移除 + 关闭窗口）。
	 * 
	 *  只删除 id 精确匹配的便利贴（filter 保留不等于 id 的），且 upsert_note 已保证
	 *  store 中 id 唯一，因此绝不影响其他便利贴。窗口按 label = `sticky-<id>` 精确匹配。
	 */
	stickyDelete: (id: string) => typedError<null, string>(__TAURI_INVOKE("sticky_delete", { id })),
	/**
	 *  贴出某分组的全部便利贴。
	 * 
	 *  已打开的窗口（含被 sticky_hide_all 隐藏的）直接**显示**并计数，而非跳过——
	 *  否则「收起全部」后无法再贴出。async：一次创建多个 WebView 窗口较慢，放后台
	 *  线程避免阻塞主线程（否则 UI 卡死）。
	 */
	stickyShowGroup: (group: string) => typedError<number, string>(__TAURI_INVOKE("sticky_show_group", { group })),
	/**  收起全部便利贴窗口（不删数据）。 */
	stickyHideAll: () => typedError<null, string>(__TAURI_INVOKE("sticky_hide_all")),
	/**
	 *  单便利贴开关（Ctrl+Shift+E / 工具箱按钮）：打开 / 关闭单便利贴窗口。
	 * 
	 *  数据唯一 + 窗口唯一：
	 *  1. store 锁内确保存在唯一 `sn-single` 记录（无历史则建默认空贴）。
	 *  2. 锁外查 `sticky-sn-single` 窗口：
	 *     - 可见 → hide（再按关闭；hide 保留窗口与 WebView，再开秒回）
	 *     - 隐藏 → show + focus（恢复打开，不重复建窗）
	 *     - 不存在 → 建窗（首次打开）
	 * 
	 *  async：创建 WebView 窗口较慢，放后台线程（同 `sticky_create`）。
	 */
	stickySingleToggle: () => typedError<StickySingleStatus, string>(__TAURI_INVOKE("sticky_single_toggle")),
	/**  单便利贴当前开关状态（工具箱按钮初始化）：窗口存在且可见 → open:true，否则 false。 */
	stickySingleStatus: () => typedError<StickySingleStatus, string>(__TAURI_INVOKE("sticky_single_status")),
	syncHomeShortcut: (shortcut: string) => __TAURI_INVOKE<ShortcutSyncResponse>("sync_home_shortcut", { shortcut }),
	syncShowShortcut: (shortcut: string) => __TAURI_INVOKE<ShortcutSyncResponse>("sync_show_shortcut", { shortcut }),
	syncUniversalScreenshotShortcut: (shortcut: string) => __TAURI_INVOKE<ShortcutSyncResponse>("sync_universal_screenshot_shortcut", { shortcut }),
	/**  同步便利贴快捷键：先做冲突校验，再取消旧的、注册新的（独立管理，不触碰其他快捷键）。 */
	syncStickyShortcut: (shortcut: string) => __TAURI_INVOKE<ShortcutSyncResponse>("sync_sticky_shortcut", { shortcut }),
	/**  同步单便利贴快捷键：先取消旧的，再注册新的；校验与其他快捷键的冲突。 */
	syncSingleStickyShortcut: (shortcut: string) => __TAURI_INVOKE<ShortcutSyncResponse>("sync_single_sticky_shortcut", { shortcut }),
	/**  同步恢复全部贴图交互快捷键：先取消旧的，再注册新的；校验与其他快捷键的冲突。 */
	syncPinRecoveryShortcut: (shortcut: string) => __TAURI_INVOKE<ShortcutSyncResponse>("sync_pin_recovery_shortcut", { shortcut }),
	/**
	 *  同步工具级拉起快捷键：全量 reconcile（增量增删）+ 冲突校验。
	 *  校验先于任何注册变更，冲突时整批拒绝（`success=false` 且不动现有注册）。
	 */
	syncToolShortcuts: (shortcuts: { [key in string]: string }) => __TAURI_INVOKE<ToolShortcutsSyncResponse>("sync_tool_shortcuts", { shortcuts }),
	/**
	 *  同步文本管线拉起快捷键：镜像 `sync_tool_shortcuts`（增量 reconcile + 交叉冲突校验，
	 *  管线键不得等于 6 个全局 role 或任一书签工具键）。
	 */
	syncPipelineShortcuts: (shortcuts: { [key in string]: string }) => __TAURI_INVOKE<PipelineShortcutsSyncResponse>("sync_pipeline_shortcuts", { shortcuts }),
	/**  获取全部闹钟（权威数据来自 store）。 */
	timerGetAlarms: () => typedError<Alarm[], string>(__TAURI_INVOKE("timer_get_alarms")),
	/**  新增闹钟（默认启用）。 */
	timerAddAlarm: (label: string, hour: number, minute: number, repeatDays: number[]) => typedError<Alarm, string>(__TAURI_INVOKE("timer_add_alarm", { label, hour, minute, repeatDays })),
	/**  更新闹钟（完整替换；用于编辑与启停开关）。 */
	timerUpdateAlarm: (alarm: Alarm) => typedError<null, string>(__TAURI_INVOKE("timer_update_alarm", { alarm })),
	/**  删除闹钟（同时清理其贪睡项与弹窗）。 */
	timerDeleteAlarm: (id: string) => typedError<null, string>(__TAURI_INVOKE("timer_delete_alarm", { id })),
	/**  获取运行中/暂停中的倒计时（无则 None）。 */
	timerGetCountdown: () => typedError<{
	id: string,
	name: string,
	/**  总时长（秒）。 */
	totalSeconds: number,
	/**  启动/继续时刻（epoch 秒）。运行中为 Some，暂停/未启动为 None。 */
	startAt: number | null,
	/**  剩余秒数：运行中为 `start_at` 时刻的锚点值（当前剩余按墙钟推算）；暂停时为权威值。 */
	remainingSeconds: number,
} | null, string>(__TAURI_INVOKE("timer_get_countdown")),
	/**  启动一个倒计时（替换已存在的运行实例）。 */
	timerStartCountdown: (name: string, totalSeconds: number) => typedError<Countdown, string>(__TAURI_INVOKE("timer_start_countdown", { name, totalSeconds })),
	/**  暂停倒计时：冻结 remaining 并持久化（start_at 置 None）。 */
	timerPauseCountdown: () => typedError<null, string>(__TAURI_INVOKE("timer_pause_countdown")),
	/**  继续倒计时：start_at 重新置为当前时刻。 */
	timerResumeCountdown: () => typedError<null, string>(__TAURI_INVOKE("timer_resume_countdown")),
	/**  取消倒计时：移除实例与弹窗。 */
	timerCancelCountdown: () => typedError<null, string>(__TAURI_INVOKE("timer_cancel_countdown")),
	/**  获取番茄钟配置与运行态。 */
	timerGetPomodoro: () => typedError<PomodoroPersist, string>(__TAURI_INVOKE("timer_get_pomodoro")),
	/**  更新番茄钟参数（非运行时生效；运行时只改配置不打断当前阶段）。 */
	timerSetPomodoroConfig: (workMinutes: number, shortBreakMinutes: number, longBreakMinutes: number, intervalForLongBreak: number) => typedError<null, string>(__TAURI_INVOKE("timer_set_pomodoro_config", { workMinutes, shortBreakMinutes, longBreakMinutes, intervalForLongBreak })),
	/**  开始（或继续）番茄钟：未运行时从当前阶段剩余时长继续；休息完成挂起时推进到工作。 */
	timerStartPomodoro: () => typedError<null, string>(__TAURI_INVOKE("timer_start_pomodoro")),
	/**  暂停番茄钟（冻结当前阶段剩余时长）。 */
	timerPausePomodoro: () => typedError<null, string>(__TAURI_INVOKE("timer_pause_pomodoro")),
	/**  跳过当前阶段：立即推进到下一阶段（不记历史）。 */
	timerSkipPhase: () => typedError<null, string>(__TAURI_INVOKE("timer_skip_phase")),
	/**  重置本轮：回到工作阶段、暂停态，保留累计工作次数。 */
	timerResetPomodoro: () => typedError<null, string>(__TAURI_INVOKE("timer_reset_pomodoro")),
	/**  获取倒计时预设（含内置）。 */
	timerGetPresets: () => typedError<CountdownPreset[], string>(__TAURI_INVOKE("timer_get_presets")),
	/**  新增自定义预设。 */
	timerAddPreset: (seconds: number, name: string | null) => typedError<CountdownPreset, string>(__TAURI_INVOKE("timer_add_preset", { seconds, name })),
	/**  删除自定义预设。 */
	timerRemovePreset: (id: string) => typedError<null, string>(__TAURI_INVOKE("timer_remove_preset", { id })),
	/**  获取整点报时开关。 */
	timerGetChime: () => typedError<boolean, string>(__TAURI_INVOKE("timer_get_chime")),
	/**  设置整点报时开关。 */
	timerSetChime: (enabled: boolean) => typedError<null, string>(__TAURI_INVOKE("timer_set_chime", { enabled })),
	/**  获取历史统计。 */
	timerGetHistory: () => typedError<HistoryEntry[], string>(__TAURI_INVOKE("timer_get_history")),
	/**  清空历史统计。 */
	timerClearHistory: () => typedError<null, string>(__TAURI_INVOKE("timer_clear_history")),
	/**  弹窗初始化：按 kind/id 读取载荷。 */
	timerGetAlert: (kind: string, id: string) => typedError<AlertPayload, string>(__TAURI_INVOKE("timer_get_alert", { kind, id })),
	/**  弹窗按钮动作：闹钟 snooze/close、倒计时 dismiss、番茄 dismiss/skip、整点 dismiss。 */
	timerAlertAction: (kind: string, action: string, id: string) => typedError<null, string>(__TAURI_INVOKE("timer_alert_action", { kind, action, id })),
	/**  前端通知显示一条 toast：存载荷、创建/复用并显示小窗，1.5s 后自动隐藏。 */
	toastShow: (message: string, isError: boolean) => typedError<null, string>(__TAURI_INVOKE("toast_show", { message, isError })),
	/**  ToastRoot 组件挂载时读取当前载荷（首次建窗兜底）。 */
	toastGet: () => __TAURI_INVOKE<{
	message: string,
	isError: boolean,
} | null>("toast_get"),
};

/* Types */
/**
 *  闹钟。`repeat_days` 空 = 单次（触发后自动 disabled）；非空 = 按周几重复
 *  （0=周日 ..=6=周六），重复闹钟保持 enabled。
 */
export type Alarm = {
	id: string,
	label: string,
	/**  小时 0..=23。 */
	hour: number,
	/**  分钟 0..=59。 */
	minute: number,
	/**  0..=6 (Sun..Sat)，空 = 单次。 */
	repeatDays: number[],
	enabled: boolean,
};

/**  弹窗载荷：弹窗初始化时按 kind/id 读取渲染所需字段。 */
export type AlertPayload = {
	kind: string,
	/**  大标题（闹钟 label / 倒计时名 / 阶段名 / "整点报时"）。 */
	title: string,
	/**  副文案。 */
	message: string,
	/**  是否显示「贪睡」按钮（闹钟）。 */
	showSnooze: boolean,
	/**  是否显示「关闭/确定」按钮。 */
	showClose: boolean,
	/**  是否显示「跳过」按钮（番茄）。 */
	showSkip: boolean,
	/**  整点报时：自动消失，无按钮。 */
	autoDismiss: boolean,
};

export type ApplyEnvWriteRequest = {
	previewId: string,
};

/**  Result returned when cancelling a session. */
export type CancelSessionResult = {
	cancelled: boolean,
	sessionId: string | null,
	generation: number | null,
};

/**  确认结果。 */
export type ConfirmSelectionResult = {
	width: number,
	height: number,
};

/**
 *  运行中（或已暂停）的倒计时实例（单实例）。
 * 
 *  `start_at: Some` = 运行中（`remaining_seconds` 是 `start_at` 时刻的锚点值，当前剩余
 *  由 `countdown_remaining` 按墙钟推算，不逐秒写 store）；
 *  `start_at: None` = 未启动或已暂停（`remaining_seconds` 为权威剩余值）。
 */
export type Countdown = {
	id: string,
	name: string,
	/**  总时长（秒）。 */
	totalSeconds: number,
	/**  启动/继续时刻（epoch 秒）。运行中为 Some，暂停/未启动为 None。 */
	startAt: number | null,
	/**  剩余秒数：运行中为 `start_at` 时刻的锚点值（当前剩余按墙钟推算）；暂停时为权威值。 */
	remainingSeconds: number,
};

/**  倒计时预设（内置 + 用户自定义）。 */
export type CountdownPreset = {
	id: string,
	seconds: number,
	name: string,
};

/**  识别出的元素（物理屏幕像素矩形 + 元数据）。 */
export type DetectedElement = {
	left: number,
	top: number,
	right: number,
	bottom: number,
	controlType: number,
	name: string,
	/**  true = 顶层窗口（控件级识别失败时的降级结果）。 */
	isWindow: boolean,
	/**
	 *  包含该元素的顶层窗口矩形（物理像素）。窗口级识别时为 None（自身即窗口）。
	 *  前端用它做「控件所在窗口去阴影」。
	 */
	windowRect: [number, number, number, number] | null,
};

export type EnvCommandError = {
	code: string,
	message: string,
};

export type EnvPlatformInfo = {
	platform: string,
	supportsDirectWrite: boolean,
	availableTargets: EnvTargetInfo[],
};

export type EnvTargetInfo = {
	id: string,
	path: string,
	exists: boolean,
	recommended: boolean,
};

export type EnvTargetPreview = {
	id: string,
	path: string,
	exists: boolean,
	action: string,
	beforeLines: string[],
	afterLines: string[],
	diff: string,
	hash: string,
	warnings: string[],
};

export type EnvVariable = {
	key: string,
	value: string,
	valueType: string,
	scope: string,
	sourceLabel: string,
	writable: boolean,
};

export type EnvWritePreview = {
	previewId: string,
	requiresConfirmation: boolean,
	targets: EnvTargetPreview[],
	warnings: string[],
};

export type GetEnvResult = {
	ok: boolean,
	value: string | null,
	variable: EnvVariable | null,
	message: string,
};

/**  历史统计条目（追加型）。 */
export type HistoryEntry = {
	/**  "countdown" | "pomodoro"。 */
	kind: string,
	/**  本次时长（秒）。 */
	seconds: number,
	/**  完成时刻（epoch 秒）。 */
	finishedAtEpochSecs: number,
};

export type HistoryImageVariant = "original" | "final";

export type HistoryManifest = {
	schemaVersion: number,
	recordId: string,
	artifactId: string,
	createdAt: number,
	width: number,
	height: number,
	originalFile: string,
	finalFile: string,
	originalBytes: number,
	finalBytes: number,
	originalDigest: string,
	finalDigest: string,
	artifactDigest: string,
	source: HistorySource,
	completed: boolean,
};

/**  对外暴露的容量设置（含可选档位）。 */
export type HistoryQuotaSettings = {
	quotaBytes: number,
	permittedQuotaBytes: number[],
};

export type HistoryRecordDetail = {
	manifest: HistoryManifest,
	originalToken: string,
	finalToken: string,
};

export type HistoryRecordSummary = {
	recordId: string,
	createdAt: number,
	width: number,
	height: number,
	totalBytes: number,
	artifactDigest: string,
	source: HistorySource,
};

export type HistorySaveAsResult = {
	saved: boolean,
	cancelled: boolean,
};

export type HistorySource = {
	kind: string,
	recordId?: string | null,
	variant?: string | null,
};

export type ListEnvResult = {
	ok: boolean,
	variables: EnvVariable[],
	message: string,
	warnings?: string[],
};

/**  单行识别结果（本期仅返回整段文本 + 平均置信度，行级信息预留）。 */
export type OcrLine = {
	text: string,
	confidence: number | null,
	bbox: [number, number, number, number] | null,
};

/**  OCR 识别结果。 */
export type OcrResult = {
	text: string,
	lines: OcrLine[],
	avgConfidence: number | null,
};

/**  覆盖层窗口初始化信息。 */
export type OverlayInitInfo = {
	sessionId: string,
	monitorIndex: number,
	desktopRect: PhysicalDesktopRectI32,
	frameToken: string,
	frameUrl: string,
	scaleFactor: number | null,
	isPrimary: boolean,
	monitorName: string,
};

export type OverlayMonitorInfo = {
	/**  覆盖层窗口 label 后缀。 */
	monitorIndex: number,
	/**  该显示器物理像素桌面矩形。 */
	desktopRect: PhysicalDesktopRectI32,
	/**  采集帧访问 token（不透明，一次性）。 */
	frameToken: string,
	/**
	 *  采集帧 URL（自定义协议 `frame-image://<token>`），前端 <img> 直接加载，
	 *  绕过 invoke JSON IPC 传输大字节数组（快得多）。
	 */
	frameUrl: string,
	/**  物理像素缩放系数。 */
	scaleFactor: number | null,
};

/**  Signed physical desktop point in virtual-desktop coordinates. */
export type PhysicalDesktopPointI32 = {
	x: number,
	y: number,
};

/**  Half-open physical desktop rectangle `[left, right) × [top, bottom)`. */
export type PhysicalDesktopRectI32 = {
	left: number,
	top: number,
	right: number,
	bottom: number,
};

export type PinCreateResult = {
	pinId: string,
	label: string,
};

export type PinState = {
	pinId: string,
	label: string,
	imageToken: string,
	width: number,
	height: number,
	zoomPercent: number,
	opacityPercent: number,
	clickThrough: boolean,
	accountedBytes: number,
	/**  旋转角度（0/90/180/270）。 */
	rotation: number,
	/**  水平翻转。 */
	flippedH: boolean,
	/**  垂直翻转。 */
	flippedV: boolean,
	/**  分组（0/1/2）。 */
	group: number,
};

export type PinTrayItem = {
	pinId: string,
	label: string,
	zoomPercent: number,
	opacityPercent: number,
	clickThrough: boolean,
};

export type PipelineShortcutsSyncResponse = {
	success: boolean,
	error: string | null,
	errors: { [key in string]: string },
};

/**  番茄钟配置。 */
export type PomodoroConfig = {
	/**  工作时长（分钟，默认 25）。 */
	workMinutes: number,
	/**  短休时长（分钟，默认 5）。 */
	shortBreakMinutes: number,
	/**  长休时长（分钟，默认 15）。 */
	longBreakMinutes: number,
	/**  每 N 个工作后进长休（默认 4）。 */
	intervalForLongBreak: number,
};

/**  番茄钟持久化体（配置 + 运行态一起存）。 */
export type PomodoroPersist = {
	config: PomodoroConfig,
	state: PomodoroState,
};

/**  番茄钟运行态。 */
export type PomodoroState = {
	running: boolean,
	/**  "work" | "short_break" | "long_break"。 */
	phase: string,
	/**  当前阶段剩余秒数。 */
	secondsLeft: number,
	/**  累计完成的工作阶段数（专注总次数）。 */
	workCount: number,
	/**  当前一轮内已完成的工作数（0..=interval_for_long_break）。 */
	inRound: number,
	/**  当前阶段启动时刻（epoch 秒），运行中为 Some。 */
	phaseStartAt: number | null,
	/**  阶段是否已完成并等待用户确认开始下一阶段（到点后挂起，点「开始下一个」才推进）。 */
	awaitingNext?: boolean,
};

export type PreviewEnvDeleteRequest = {
	key: string,
};

export type PreviewEnvWriteRequest = {
	key: string,
	value: string,
	targets?: string[],
};

/**  屏蔽时段（HH:MM，无日期；start > end 表示跨天）。 */
export type QuietPeriod = {
	start: string,
	end: string,
};

/**  滚动进度（next 返回）。 */
export type ScrollProgress = {
	stitchedHeight: number,
};

/**  publish 返回。 */
export type ScrollPublishResult = {
	recordId: string,
	width: number,
	height: number,
};

/**  滚动截图会话信息（start 返回）。 */
export type ScrollStartResult = {
	sessionId: string,
	stitchedHeight: number,
};

/**  停止返回。 */
export type ScrollStopResult = {
	stitchedHeight: number,
	width: number,
	/**  scroll-image 协议访问 token（用于预览拼接长图）。 */
	previewToken: string,
};

/**  `sedentary_get_config` 返回体。 */
export type SedentaryGetConfigResponse = {
	enabled: boolean,
	remindMinutes: number,
	idleResetMinutes: number,
	message: string,
	/**  视频播放开关（弹窗据此决定是否进入视频阶段）。 */
	videoEnabled: boolean,
	/**  提醒视频绝对路径；视频缺失/复制失败时为空串（无视频模式）。 */
	videoPath: string,
	/**  当前平台是否支持空闲检测（Windows 为 true）。 */
	supported: boolean,
	/**  屏蔽时段列表（空 = 不屏蔽）。 */
	quietPeriods: QuietPeriod[],
};

/**  `sedentary_get_state` 返回体。 */
export type SedentaryGetStateResponse = {
	enabled: boolean,
	sittingSeconds: number,
	remindSeconds: number,
	/**  当前是否处于屏蔽时段。 */
	quietActive: boolean,
	/**  距屏蔽结束剩余秒数（非屏蔽中为 0）。 */
	quietRemainingSeconds: number,
};

export type SetEnvResult = {
	ok: boolean,
	message: string,
	warnings: string[],
};

export type ShortcutSyncResponse = {
	success: boolean,
	requestedShortcut: string,
	registeredShortcut: string | null,
	error: string | null,
};

/**  会话开始时返回给前端的覆盖层信息。 */
export type StartOverlaySession = {
	sessionId: string,
	/**  每个覆盖层窗口一条。 */
	monitors: OverlayMonitorInfo[],
};

/**  便利贴数据（持久化到 store）。 */
export type StickyNoteData = {
	id: string,
	text: string,
	/**  预设色 key（mint/yellow/blue/pink/purple）。 */
	color: string,
	/**  分组名。 */
	group: string,
	x: number,
	y: number,
	width: number,
	height: number,
};

/**  单便利贴开关状态（`sticky_single_toggle` / `sticky_single_status` 返回）。 */
export type StickySingleStatus = {
	/**  toggle 后 / 当前单便利贴窗口是否可见。 */
	open: boolean,
};

export type ToastPayload = {
	message: string,
	isError: boolean,
};

export type ToolShortcutsSyncResponse = {
	success: boolean,
	error: string | null,
	errors: { [key in string]: string },
};

/**  删除操作的收据：记录 ID 与可撤销截止时间。 */
export type TrashReceipt = {
	recordId: string,
	deleteAfter: number,
};

/**  完成动作。 */
export type UniversalFinishAction = "copy" | "pin" | "save_as";

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

